AY2324S1-CS2103T-W17-3/tp

- docs/AboutUs.md
Closes https://github.com/AY2324S1-CS2103T-W17-3/tp/issues/10.
> Add Duy's AboutUs info

- docs/team/jedkohjk.md
> Add skeletal PPP for Jed

- docs/team/jeffrey-jian.md
Closes #23
Add Skeletal PPP for Jeffrey
> Add skeletal Jeffrey's PPP

- docs/team/nathanielcalimag.md
Closes AY2324S1-CS2103T-W17-3/tp#21
> [PPP] Add Nathaniel's skeletal PPP

- docs/team/ncduy0303.md
> [PPP] Add Duy's skeletal PPP

- README.md
> [README] Update README page

- docs/DeveloperGuide.md
Closes AY2324S1-CS2103T-W17-3/tp#25
> [DG] Update NFRs and glossary

- docs/_config.yml
- docs/_sass/minima/_base.scss
- docs/index.md
- Update the details in `index.md`, `_base.scss`, `_config.yml` to match our application
- Close #42
> [Docs] Update website information

- docs/DeveloperGuide.md
> [DG] Add use cases for v1.2

- docs/DeveloperGuide.md
Added v1.1 use cases.
Fixed formatting, labelled UCs.
> [DG] Add v1.1 Use Cases

- src/main/java/seedu/address/model/transaction/Amount.java
- src/main/java/seedu/address/model/transaction/Transaction.java
- src/test/java/seedu/address/model/transaction/AmountTest.java
- src/test/java/seedu/address/model/transaction/TransactionTest.java
- src/test/java/seedu/address/testutil/TransactionBuilder.java
> [Implementation] Add Transaction model

- src/main/java/seedu/address/ui/MainWindow.java
- src/main/resources/view/MainWindow.fxml
> Split UI panes

- src/main/java/seedu/address/model/AddressBook.java
- src/main/java/seedu/address/model/Model.java
- src/main/java/seedu/address/model/ModelManager.java
- src/main/java/seedu/address/model/transaction/Transaction.java
- src/main/java/seedu/address/model/transaction/UniqueTransactionList.java
- src/main/java/seedu/address/model/transaction/exceptions/DuplicateTransactionException.java
- src/test/java/seedu/address/logic/commands/AddCommandTest.java
- src/test/java/seedu/address/model/AddressBookTest.java
- src/test/java/seedu/address/model/ModelManagerTest.java
- src/test/java/seedu/address/model/transaction/TransactionTest.java
- src/test/java/seedu/address/testutil/TransactionBuilder.java
- Add `filteredTransactions` which is similar to `filteredPersons`
- Add transaction-related methods to `Model.java`
- Add set and remove transaction method to `AddressBook.java`
> Integrate Transaction into Model

- src/main/java/seedu/address/storage/JsonAdaptedExpense.java
Rename `JsonAdaptedExpense`'s field from `name` to `personName` to align with the `Expense` class.
> Rename JSON expense field

- src/main/java/seedu/address/storage/JsonAdaptedExpense.java
- src/main/java/seedu/address/storage/JsonSerializableAddressBook.java
Include transactions when saving to storage
> Fix storage saving bug

- src/main/java/seedu/address/model/person/Name.java
- src/main/java/seedu/address/model/util/SampleDataUtil.java
- src/test/data/JsonSerializableAddressBookTest/typicalAddressBook.json
- src/test/java/seedu/address/logic/commands/AddPersonCommandIntegrationTest.java
- src/test/java/seedu/address/logic/commands/DeletePersonCommandTest.java
- src/test/java/seedu/address/logic/commands/EditPersonCommandTest.java
- src/test/java/seedu/address/logic/commands/FindCommandTest.java
- src/test/java/seedu/address/logic/commands/ListPersonCommandTest.java
- src/test/java/seedu/address/logic/commands/ListTransactionCommandTest.java
- src/test/java/seedu/address/model/AddressBookTest.java
- src/test/java/seedu/address/model/ModelManagerTest.java
- src/test/java/seedu/address/model/transaction/TransactionContainsPersonNamesPredicateTest.java
- src/test/java/seedu/address/model/transaction/TransactionTest.java
- src/test/java/seedu/address/model/transaction/UniqueTransactionListTest.java
- src/test/java/seedu/address/storage/JsonAdaptedTransactionTest.java
- src/test/java/seedu/address/storage/JsonAddressBookStorageTest.java
- src/test/java/seedu/address/storage/JsonSerializableAddressBookTest.java
- src/test/java/seedu/address/storage/StorageManagerTest.java
- src/test/java/seedu/address/testutil/TypicalAddressBook.java
- src/test/java/seedu/address/testutil/TypicalExpenses.java
- src/test/java/seedu/address/testutil/TypicalPersons.java
- src/test/java/seedu/address/testutil/TypicalTransactions.java
Closes #70 
- Create `Name.SELF` constant
- Create sample transactions in `SampleDataUtil`
- Rename `typicalPersonsAddressBook.json' to `typicalAddressBook.json' and populate with sample transaction data.
- Update `TypicalExpenses` to use the name of `BENSON` as opposed to `BOB` to align with the `TypicalPersons` data.
- Update tests to utilise the `BENSON` person as opposed to `BOB` to account for the above change.
> [Task] Add sample transaction data

- src/main/java/seedu/address/model/AddressBook.java
- src/main/java/seedu/address/model/person/UniquePersonList.java
- src/main/java/seedu/address/model/transaction/Transaction.java
- src/main/java/seedu/address/model/transaction/UniqueTransactionList.java
- src/main/java/seedu/address/model/transaction/expense/Weight.java
- src/main/java/seedu/address/ui/ExpenseListView.java
- src/main/java/seedu/address/ui/TransactionCard.java
- src/test/java/seedu/address/model/transaction/TransactionTest.java
- src/test/java/seedu/address/model/transaction/expense/WeightTest.java
- src/test/java/seedu/address/storage/JsonAddressBookStorageTest.java
> Aggregate deleted persons to others

- docs/UserGuide.md
> Update User Guide and rename expenses to transactions

- src/main/java/seedu/address/ui/TransactionCard.java
The minute used to display the month
> Fix UI datetime format

- src/main/java/seedu/address/logic/commands/AddPersonCommand.java
- src/main/java/seedu/address/logic/parser/AddPersonCommandParser.java
- src/main/java/seedu/address/model/person/Name.java
- src/main/java/seedu/address/model/person/Person.java
- src/test/data/JsonSerializableAddressBookTest/typicalAddressBook.json
- src/test/java/seedu/address/logic/commands/CommandTestUtil.java
- src/test/java/seedu/address/logic/parser/AddPersonCommandParserTest.java
- src/test/java/seedu/address/model/person/NameTest.java
- src/test/java/seedu/address/model/person/PersonTest.java
> Block adding persons with reserve names

- src/main/java/seedu/address/model/transaction/Timestamp.java
- src/main/java/seedu/address/model/transaction/Transaction.java
- src/main/java/seedu/address/model/transaction/UniqueTransactionList.java
- src/main/java/seedu/address/ui/TransactionCard.java
> Sort transactions by recency

- src/main/java/seedu/address/model/person/Name.java
- src/main/java/seedu/address/model/transaction/Amount.java
- src/main/java/seedu/address/model/transaction/expense/Weight.java
- src/main/java/seedu/address/model/util/SampleDataUtil.java
- src/main/java/seedu/address/storage/JsonAdaptedExpense.java
- src/main/java/seedu/address/storage/JsonAdaptedTransaction.java
- src/test/java/seedu/address/model/person/NameTest.java
- src/test/java/seedu/address/model/transaction/AmountTest.java
- src/test/java/seedu/address/model/transaction/expense/WeightTest.java
- src/test/java/seedu/address/storage/JsonAdaptedExpenseTest.java
- src/test/java/seedu/address/storage/JsonAdaptedTransactionTest.java
- Update `Weight` and `Amount` to be stored in the JSON file as fractions, rather than rounding to 2 decimal places.
- Update `'SELF'` to `'Self'`.
- Added a test to verify case-insensitivity of `Name`.
- Made hashing of `Name` case insensitive.
> [Task] Add minor fixes to storage

- src/main/java/seedu/address/model/person/Name.java
- src/main/java/seedu/address/model/transaction/Amount.java
- src/main/java/seedu/address/model/transaction/expense/Weight.java
- src/main/java/seedu/address/model/util/SampleDataUtil.java
- src/main/java/seedu/address/storage/JsonAdaptedExpense.java
- src/main/java/seedu/address/storage/JsonAdaptedTransaction.java
- src/test/java/seedu/address/model/person/NameTest.java
- src/test/java/seedu/address/model/transaction/AmountTest.java
- src/test/java/seedu/address/model/transaction/expense/WeightTest.java
- src/test/java/seedu/address/storage/JsonAdaptedExpenseTest.java
- src/test/java/seedu/address/storage/JsonAdaptedTransactionTest.java
Reverts AY2324S1-CS2103T-W17-3/tp#105
> Revert "[Task] Add minor fixes to storage"

- src/main/java/seedu/address/model/person/Name.java
- src/main/java/seedu/address/model/util/SampleDataUtil.java
- src/main/java/seedu/address/storage/JsonAdaptedExpense.java
- src/main/java/seedu/address/storage/JsonAdaptedTransaction.java
- src/test/java/seedu/address/model/person/NameTest.java
> [Task] Fix name bugs

- src/main/java/seedu/address/ui/ExpenseListView.java
- src/main/java/seedu/address/ui/NameLabel.java
- src/main/java/seedu/address/ui/TransactionCard.java
> Refactor UI

- src/main/java/seedu/address/logic/Logic.java
- src/main/java/seedu/address/logic/LogicManager.java
- src/main/java/seedu/address/model/AddressBook.java
- src/main/java/seedu/address/model/Model.java
- src/main/java/seedu/address/model/ModelManager.java
- src/main/java/seedu/address/model/transaction/UniqueTransactionList.java
- src/main/java/seedu/address/ui/MainWindow.java
- src/main/java/seedu/address/ui/PersonCard.java
- src/main/java/seedu/address/ui/PersonListPanel.java
- src/main/resources/view/PersonListCard.fxml
- src/test/java/seedu/address/logic/commands/AddPersonCommandTest.java
- src/test/java/seedu/address/logic/commands/AddTransactionCommandTest.java
- src/test/java/seedu/address/model/transaction/UniqueTransactionListTest.java
> Add balance to UI

- docs/DeveloperGuide.md
- docs/UserGuide.md
- src/main/java/seedu/address/logic/parser/ArgumentTokenizer.java
- src/main/java/seedu/address/logic/parser/CliSyntax.java
- src/main/java/seedu/address/logic/parser/Prefix.java
- src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
Closes #118 
Note: Not sure if Index will have its own "i=" prefix? It doesnt have for edit and delete command. Updated the UG accordingly
DG diagrams for the original addressbook will also have to change
> Change prefix to use "=" instead of "/"

- src/main/java/seedu/address/model/AddressBook.java
- src/main/java/seedu/address/model/transaction/Transaction.java
- src/main/java/seedu/address/model/transaction/UniqueTransactionList.java
> Cascade edited names to transactions

- src/main/java/seedu/address/logic/commands/EditPersonCommand.java
- src/test/java/seedu/address/logic/commands/EditPersonCommandTest.java
> Show reserved name error message if editing a persons name to a reserved name

- src/main/java/seedu/address/logic/commands/EditTransactionCommand.java
- src/main/java/seedu/address/logic/parser/EditTransactionCommandParser.java
- src/test/java/seedu/address/logic/parser/EditTransactionCommandParserTest.java
> [Task] Editable transaction payee

- src/main/java/seedu/address/ui/TransactionCard.java
\+ means the person owes us
\- means we owe the person
> Make the lists consistent in the +/- sign of balances

- build.gradle
This was one of the tp tasks this week
> Enable gradle assertions

- src/main/java/seedu/address/model/AddressBook.java
- src/main/java/seedu/address/model/transaction/Transaction.java
- src/main/java/seedu/address/model/transaction/UniqueTransactionList.java
> Synchronise names in lists

- src/main/java/seedu/address/model/transaction/Transaction.java
Fix a regression issue in #148
Merged without approvals due to urgency
> Fix oudated usage of `Expense`

- src/main/java/seedu/address/ui/NameLabel.java
> [Enhancement] Update name label to be user friendly

- src/main/java/seedu/address/logic/commands/EditTransactionCommand.java
- src/test/java/seedu/address/logic/commands/EditTransactionCommandTest.java
> EditTransaction command checks for irrelevant transactions

- src/main/java/seedu/address/logic/Messages.java
- src/main/java/seedu/address/logic/commands/AddTransactionCommand.java
- src/main/java/seedu/address/logic/commands/DeleteTransactionCommand.java
- src/main/java/seedu/address/logic/commands/DuplicateTransactionCommand.java
- src/main/java/seedu/address/logic/commands/EditTransactionCommand.java
- src/main/java/seedu/address/logic/parser/AddressBookParser.java
- src/main/java/seedu/address/logic/parser/DuplicateTransactionCommandParser.java
- src/test/java/seedu/address/logic/commands/AddTransactionCommandIntegrationTest.java
- src/test/java/seedu/address/logic/commands/AddTransactionCommandTest.java
- src/test/java/seedu/address/logic/commands/DeleteTransactionCommandTest.java
- src/test/java/seedu/address/logic/commands/DuplicateTransactionCommandTest.java
- src/test/java/seedu/address/logic/commands/EditTransactionCommandTest.java
- src/test/java/seedu/address/logic/parser/DuplicateTransactionCommandParserTest.java
> Add duplicateTransaction command by index

- src/test/java/seedu/address/logic/commands/AddTransactionCommandIntegrationTest.java
- src/test/java/seedu/address/logic/commands/AddTransactionCommandTest.java
> Update `addTransaction` integration tests

- src/main/java/seedu/address/storage/JsonAdaptedPerson.java
- src/test/java/seedu/address/storage/JsonAdaptedPersonTest.java
> Account for reserved names in data file

- build.gradle
- src/main/resources/view/CommandBox.fxml
- src/main/resources/view/HelpWindow.fxml
- src/main/resources/view/MainWindow.fxml
- src/main/resources/view/PersonListCard.fxml
- src/main/resources/view/PersonListPanel.fxml
- src/main/resources/view/PortionListView.fxml
- src/main/resources/view/ResultDisplay.fxml
- src/main/resources/view/TransactionListCard.fxml
- src/main/resources/view/TransactionListPanel.fxml
> Change JavaFX version to fix ListView

- src/main/java/seedu/address/logic/commands/AddTransactionCommand.java
- src/main/java/seedu/address/logic/commands/EditTransactionCommand.java
- src/main/java/seedu/address/model/transaction/Timestamp.java
- src/main/java/seedu/address/model/transaction/Transaction.java
- src/main/java/seedu/address/model/util/SampleDataUtil.java
- src/main/java/seedu/address/ui/TransactionCard.java
- src/test/data/JsonSerializableAddressBookTest/typicalAddressBook.json
- src/test/java/seedu/address/logic/commands/CommandTestUtil.java
- src/test/java/seedu/address/logic/commands/EditTransactionCommandTest.java
- src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
- src/test/java/seedu/address/logic/parser/EditTransactionCommandParserTest.java
- src/test/java/seedu/address/model/transaction/TimestampTest.java
- src/test/java/seedu/address/model/transaction/TransactionTest.java
- src/test/java/seedu/address/testutil/TransactionBuilder.java
- src/test/java/seedu/address/testutil/TypicalTransactions.java
> Make time format friendly

- src/main/java/seedu/address/logic/commands/ClearCommand.java
This reverts commit 60eb1d03b3932ee2e93281720a64a0f26c64bf7c.
Closes #193. I reverted the command to its orginal behaviour.
> Revert "Fix clear command"

- src/main/resources/view/ResultDisplay.fxml
> [Enhancement] Add wrap text

- src/main/java/seedu/address/commons/core/Config.java
- src/main/java/seedu/address/commons/util/ConfigUtil.java
- src/test/data/ConfigUtilTest/NullPathConfig.json
- src/test/java/seedu/address/commons/util/ConfigUtilTest.java
> Accept null values in config file

- src/main/java/seedu/spendnsplit/commons/util/FractionUtil.java
- src/main/java/seedu/spendnsplit/model/SpendNSplit.java
- src/test/java/seedu/spendnsplit/commons/util/FractionUtilTest.java
> Fix sorting

- src/main/java/seedu/spendnsplit/logic/Logic.java
- src/main/java/seedu/spendnsplit/logic/commands/AddPersonCommand.java
- src/main/java/seedu/spendnsplit/logic/commands/AddTransactionCommand.java
- src/main/java/seedu/spendnsplit/logic/commands/ClearCommand.java
- src/main/java/seedu/spendnsplit/logic/commands/DeletePersonCommand.java
- src/main/java/seedu/spendnsplit/logic/commands/DeleteTransactionCommand.java
- src/main/java/seedu/spendnsplit/logic/commands/DuplicateTransactionCommand.java
- src/main/java/seedu/spendnsplit/logic/commands/EditPersonCommand.java
- src/main/java/seedu/spendnsplit/logic/commands/EditTransactionCommand.java
- src/main/java/seedu/spendnsplit/logic/commands/ExitCommand.java
- src/main/java/seedu/spendnsplit/logic/commands/ListPersonCommand.java
- src/main/java/seedu/spendnsplit/logic/commands/SettlePersonCommand.java
- src/main/java/seedu/spendnsplit/logic/commands/UpdatePortionCommand.java
- src/main/java/seedu/spendnsplit/model/person/Address.java
- src/main/java/seedu/spendnsplit/model/person/Email.java
- src/main/java/seedu/spendnsplit/model/person/Name.java
- src/main/java/seedu/spendnsplit/model/person/Person.java
- src/main/java/seedu/spendnsplit/model/person/Phone.java
- src/main/java/seedu/spendnsplit/model/person/TelegramHandle.java
- src/main/java/seedu/spendnsplit/model/tag/Tag.java
- src/main/java/seedu/spendnsplit/model/transaction/Amount.java
- src/main/java/seedu/spendnsplit/model/transaction/Description.java
- src/main/java/seedu/spendnsplit/model/transaction/Timestamp.java
- src/main/java/seedu/spendnsplit/model/transaction/Transaction.java
- src/test/java/seedu/spendnsplit/logic/commands/DeletePersonCommandTest.java
- src/test/java/seedu/spendnsplit/logic/commands/DuplicateTransactionCommandTest.java
- src/test/java/seedu/spendnsplit/logic/commands/EditPersonCommandTest.java
- src/test/java/seedu/spendnsplit/logic/commands/EditTransactionCommandTest.java
> Rename address book as spendnsplit

- docs/UserGuide.md
> Fix broken UG images

- docs/index.md
> Update index document

- src/main/java/seedu/spendnsplit/logic/parser/CommandAliasMap.java
> Fix message formatting for duplicate alias

- src/main/java/seedu/spendnsplit/model/transaction/Description.java
> Update message constraint

- docs/AboutUs.md
- docs/DeveloperGuide.md
- docs/UserGuide.md
- docs/team/jedkohjk.md
- docs/team/jeffrey-jian.md
- docs/team/wui-hong.md
> Add planned enhancement for strong list input validation

- src/main/java/seedu/spendnsplit/logic/commands/UpdatePortionCommand.java
Removed all unnecessary TODOs created by us.
> Remove unnecessary TODOs

- docs/UserGuide.md
> Add explanation on relevant transactions

- docs/AboutUs.md
- docs/DeveloperGuide.md
- docs/UserGuide.md
- docs/team/jedkohjk.md
- docs/team/jeffrey-jian.md
- docs/team/wui-hong.md
> Add planned enhancement for space insensitive names

- docs/UserGuide.md
> Add clarification on command case sensitivity

- docs/DeveloperGuide.md
- docs/UserGuide.md
- docs/_includes/note.html
Previously, alerts were not displaying correctly.
> Fix alerts in UG

- docs/DeveloperGuide.md
To avoid merge conflicts when working simultaneously on different sections
> Add headers to implementation section of DG

- src/main/java/seedu/spendnsplit/storage/JsonAdaptedPerson.java
- src/main/java/seedu/spendnsplit/storage/JsonSerializableSpendNSplitBook.java
- src/test/data/JsonSerializableSpendNSplitBookTest/nullValuesSpendNSplitBook.json
- src/test/java/seedu/spendnsplit/storage/JsonSerializableSpendNSplitTest.java
> Handle null values in json file

- docs/UserGuide.md
Pending add page breaks to convert to PDF
> [UG] Polish up glossary

- docs/AboutUs.md
Currently, the `|` is causing some formatting issue. I think too many PRs have been invested into the about us page.
> Update About Us format

- README.md
- docs/DeveloperGuide.md
- docs/UserGuide.md
- docs/_config.yml
- docs/_sass/minima/_base.scss
- docs/index.md
- docs/team/jedkohjk.md
- docs/team/jeffrey-jian.md
- docs/team/nathanielcalimag.md
- docs/team/ncduy0303.md
- docs/team/wui-hong.md
- src/main/java/seedu/spendnsplit/MainApp.java
- src/main/resources/view/MainWindow.fxml
> Standardize app name
